apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: demo-instrumentation
spec:
  exporter:
    endpoint: http://otel-collector.monitoring.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: '1'
  java:
    env:
      - name: OTEL_INSTRUMENTATION_KAFKA_ENABLED
        value: "false"
      - name: OTEL_INSTRUMENTATION_REDISCALA_ENABLED
        value: "false"
      - name: OTEL_JMX_TARGET_SYSTEM
        value: jvm
      - name: OTEL_METRICS_EXPORTER
        value: prometheus
      - name: OTEL_EXPORTER_PROMETHEUS_PORT
        value: '9464'
      - name: OTEL_SERVICE_NAME
        value: ${service_name}